CREATE TABLE "CMT_NAMED_CONFIG2" (
     "NC_ID" number(19,0),
     "ABA_BLOCKSET" number(10,0),
     "ABA_SINGLESET" number(10,0),
     "ABA_MATCHES" number(10,0),
     "ABA_SINGLETABLE" number(10,0),
     "BLOCKING_CONF" varchar2(255),
     "NC_DESC" varchar2(255),
     "NC_NAME" varchar2(255),
     "DATA_SOURCE" varchar2(255),
     "HIGH_THRESHOLD" float,
     "CLASS" varchar2(255),
     "LOW_THRESHOLD" float,
     "MODEL" varchar2(255),
     "OABA_INTERVAL" number(10,0),
     "OABA_BLOCKSIZE" number(10,0),
     "OABA_CHUNKSIZE" number(10,0),
     "OABA_MATCHES" number(10,0),
     "OABA_OVERSIZE" number(10,0),
     "OABA_SINGLE" number(10,0),
     "OABA_OSFIELDS" number(10,0),
     "OPTLOCK" number(10,0),
     "QUERY_DBCONF" varchar2(255),
     "QUERY_RS_DEDUPED" number(1,0),
     "QUERY_SQL" varchar2(255),
     "RS_TYPE" varchar2(255),
     "REF_DBACC" varchar2(255),
     "REF_DBCONF" varchar2(255),
     "REF_DBREAD" varchar2(255),
     "REF_SQL" varchar2(255),
     "RIGOR" varchar2(255),
     "FILE_URI" varchar2(255),
     "SVR_FILES_COUNT" number(10,0),
     "SVR_FILE_ENTRIES" number(10,0),
     "SVR_THREADS" number(10,0),
     "TASK" varchar2(255),
     "FORMAT" varchar2(255),
     "GRAPH" varchar2(255),
     "UUID" varchar2(255)
)
;



