// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.custom.mci.internal.MciRecords;
import com.choicemaker.cm.core.*;
import com.choicemaker.cm.core.base.*;
import java.util.logging.*;
import com.choicemaker.util.StringUtils;







import com.choicemaker.cm.testobjects.mci.MciRecords.Ethnicity;
import com.choicemaker.cm.testobjects.mci.MciRecords.EthnicityBase;
import com.choicemaker.cm.testobjects.mci.MciRecords.PatientBase;


import java.util.*;

public class EthnicityImpl implements BaseRecord, Ethnicity {
private static Logger logger = Logger.getLogger(com.choicemaker.cm.custom.mci.internal.MciRecords.EthnicityImpl.class.getName());
public static EthnicityImpl[] __zeroArray = new EthnicityImpl[0];
public PatientImpl outer;
public PatientBase getOuter() {
return outer;
}
public void setOuter(PatientBase outer) {
this.outer = (PatientImpl)outer;
}
public boolean __v_ethnicity_cd;
public String ethnicity_cd;
public boolean isEthnicity_cdValid() {
return __v_ethnicity_cd;
}
public String getEthnicity_cd() {
return ethnicity_cd;
}
public EthnicityImpl(EthnicityBase __o) {
ethnicity_cd = __o.getEthnicity_cd();
}
public EthnicityImpl() {
}
public void computeValidityAndDerived(DerivedSource __src) {
java.lang.String __tmpStr;
try {
__v_ethnicity_cd = StringUtils.nonEmptyString(ethnicity_cd) && !ethnicity_cd.equals("9");
} catch(Exception __ex) {
logger.severe("Computing validity and derived of EthnicityImpl" + __ex);
}
}
public void resetValidityAndDerived(DerivedSource __src) {
}
public static EthnicityImpl instance() {
EthnicityImpl tmpInstance = new EthnicityImpl();
return tmpInstance;
}
}
