// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.custom.mci.gend.internal.MciRecords;
import com.choicemaker.cm.core.*;
import com.choicemaker.cm.core.base.*;
import com.choicemaker.cm.core.util.*;
import com.choicemaker.util.*;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JLabel;
import com.choicemaker.util.StringUtils;
import com.choicemaker.cm.custom.mci.encryption.*;
import com.choicemaker.cm.custom.mci.matching.*;
import com.choicemaker.cm.custom.mci.nameparser.*;
import com.choicemaker.cm.custom.mci.validation.*;
import com.choicemaker.cm.matching.en.*;
import com.choicemaker.cm.matching.en.us.*;
import com.choicemaker.cm.matching.gen.*;
import com.choicemaker.cm.validation.eclipse.*;
import com.choicemaker.cm.validation.eclipse.impl.*;
import java.util.*;
public class AddressImpl____descriptor implements com.choicemaker.cm.core.Descriptor {
public static com.choicemaker.cm.core.Descriptor instance = new AddressImpl____descriptor();
private static HashMap m;
private static ColumnDefinition[] cols = {
new ColumnDefinition("addr_id", "addr_id", 100, JLabel.CENTER),
new ColumnDefinition("boro_cd", "boro_cd", 100, JLabel.CENTER),
new ColumnDefinition("bin", "bin", 100, JLabel.CENTER),
new ColumnDefinition("house_no", "house_no", 100, JLabel.CENTER),
new ColumnDefinition("street_cd", "street_cd", 100, JLabel.CENTER),
new ColumnDefinition("street_name", "street_name", 100, JLabel.CENTER),
new ColumnDefinition("city_name", "city_name", 100, JLabel.CENTER),
new ColumnDefinition("state_cd", "state_cd", 100, JLabel.CENTER),
new ColumnDefinition("zipcode", "zipcode", 100, JLabel.CENTER)};
private static com.choicemaker.cm.core.Descriptor[] children = {
RelImpl____descriptor.instance};
public boolean[] getEditable(DerivedSource src) {
return new boolean[] {
true,
true,
true,
true,
true,
true,
true,
true,
true};
}
public String getName() {
return "address";
}
public String getRecordName() {
return "address";
}
public boolean isStackable() {
return true;
}
public ColumnDefinition[] getColumnDefinitions() {
return cols;
}
public Descriptor[] getChildren() {
return children;
}
public Record[][] getChildRecords(Record ri) {
return null;
}
public String getValueAsString(Record ri, int row, int col) {
PatientImpl r0 = (PatientImpl)ri;
int cur = 0;
if(cur + r0.address.length <= row) {
cur += r0.address.length;
} else {
switch(col) {
case 0:
return String.valueOf(r0.address[row-cur].addr_id);
case 1:
return r0.address[row-cur].boro_cd == '\0' ? "" : String.valueOf(r0.address[row-cur].boro_cd);
case 2:
return String.valueOf(r0.address[row-cur].bin);
case 3:
return r0.address[row-cur].house_no;
case 4:
return r0.address[row-cur].street_cd;
case 5:
return r0.address[row-cur].street_name;
case 6:
return r0.address[row-cur].city_name;
case 7:
return r0.address[row-cur].state_cd;
case 8:
return r0.address[row-cur].zipcode;
default:
throw new IndexOutOfBoundsException();
}
}
throw new IndexOutOfBoundsException();
}
public Object getValue(Record ri, int row, int col) {
PatientImpl r0 = (PatientImpl)ri;
int cur = 0;
if(cur + r0.address.length <= row) {
cur += r0.address.length;
} else {
switch(col) {
case 0:
return new Long(r0.address[row-cur].addr_id);
case 1:
return new Character(r0.address[row-cur].boro_cd);
case 2:
return new Long(r0.address[row-cur].bin);
case 3:
return r0.address[row-cur].house_no;
case 4:
return r0.address[row-cur].street_cd;
case 5:
return r0.address[row-cur].street_name;
case 6:
return r0.address[row-cur].city_name;
case 7:
return r0.address[row-cur].state_cd;
case 8:
return r0.address[row-cur].zipcode;
default:
throw new IndexOutOfBoundsException();
}
}
throw new IndexOutOfBoundsException();
}
public Class getHandledClass() {
return AddressImpl.class;
}
public boolean setValue(Record ri, int row, int col, String value) {
try {
PatientImpl r0 = (PatientImpl)ri;
int cur = 0;
if(cur + r0.address.length <= row) {
cur += r0.address.length;
} else {
switch(col) {
case 0:
r0.address[row-cur].addr_id = value.length() == 0 ? (long)0 : Long.parseLong(value);
break;
case 1:
r0.address[row-cur].boro_cd = value.length() == 0 ? (char)0 : StringUtils.getChar(value);
break;
case 2:
r0.address[row-cur].bin = value.length() == 0 ? (long)0 : Long.parseLong(value);
break;
case 3:
r0.address[row-cur].house_no = value;
break;
case 4:
r0.address[row-cur].street_cd = value;
break;
case 5:
r0.address[row-cur].street_name = value;
break;
case 6:
r0.address[row-cur].city_name = value;
break;
case 7:
r0.address[row-cur].state_cd = value;
break;
case 8:
r0.address[row-cur].zipcode = value;
break;
default:
throw new IndexOutOfBoundsException();
}
return true;}
throw new IndexOutOfBoundsException();
} catch(Exception ex) {
return false;
}
}
public boolean getValidity(Record ri, int row, int col) {
PatientImpl r0 = (PatientImpl)ri;
int cur = 0;
if(cur + r0.address.length <= row) {
cur += r0.address.length;
} else {
switch(col) {
case 0:
return r0.address[row-cur].__v_addr_id;
case 1:
return r0.address[row-cur].__v_boro_cd;
case 2:
return r0.address[row-cur].__v_bin;
case 3:
return r0.address[row-cur].__v_house_no;
case 4:
return r0.address[row-cur].__v_street_cd;
case 5:
return r0.address[row-cur].__v_street_name;
case 6:
return r0.address[row-cur].__v_city_name;
case 7:
return r0.address[row-cur].__v_state_cd;
case 8:
return r0.address[row-cur].__v_zipcode;
default:
throw new IndexOutOfBoundsException();
}
}
throw new IndexOutOfBoundsException();
}
public void addRow(int row, boolean above, Record ri) {
PatientImpl r0 = (PatientImpl)ri;
if(!above) {
++row;
};
int cur = 0;
if(cur + r0.address.length < row || (above && cur + r0.address.length == row && row != 0)) {
cur += r0.address.length;
} else {
AddressImpl[] tmp = new AddressImpl[r0.address.length + 1];
System.arraycopy(r0.address, 0, tmp, 0, (row - cur));
tmp[(row - cur)] = AddressImpl.instance();
System.arraycopy(r0.address, (row - cur), tmp, (row - cur) + 1, tmp.length - 1 - (row - cur));
r0.address = tmp;
return;}
throw new IndexOutOfBoundsException();
}
public void deleteRow(Record ri, int row) {
PatientImpl r0 = (PatientImpl)ri;
int cur = 0;
if(cur + r0.address.length <= row) {
cur += r0.address.length;
} else {
AddressImpl[] tmp = new AddressImpl[r0.address.length - 1];
System.arraycopy(r0.address, 0, tmp, 0, (row - cur));
System.arraycopy(r0.address, (row - cur) + 1, tmp, (row - cur), tmp.length - (row - cur));
r0.address = tmp;
return;}
throw new IndexOutOfBoundsException();
}
public int getColumnCount() {
return cols.length;
}
public int getRowCount(Record ri) {
PatientImpl r0 = (PatientImpl)ri;
int num = 0;
num += r0.address.length;
return num;
}

public int getColumnIndexByName(String name) {
if(m == null) {
m = new HashMap(cols.length);
for(int i = 0; i < cols.length; ++i) {
m.put(cols[i].getFieldName(), new Integer(i));
}
}
Object o = m.get(name);
if(o == null) {
return -1;
} else {
return ((Integer)o).intValue();
}
}
}
