// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.custom.mci.gend.MciRecords;
import com.choicemaker.cm.core.*;
import com.choicemaker.cm.core.base.*;
import java.util.logging.*;
import com.choicemaker.util.StringUtils;
import com.choicemaker.cm.custom.mci.encryption.*;
import com.choicemaker.cm.custom.mci.matching.*;
import com.choicemaker.cm.custom.mci.nameparser.*;
import com.choicemaker.cm.custom.mci.validation.*;
import com.choicemaker.cm.matching.en.*;
import com.choicemaker.cm.matching.en.us.*;
import com.choicemaker.cm.matching.gen.*;
import com.choicemaker.cm.testobjects.mci.MciRecords.Mothers;
import com.choicemaker.cm.testobjects.mci.MciRecords.MothersBase;
import com.choicemaker.cm.testobjects.mci.MciRecords.PatientBase;
import com.choicemaker.cm.validation.eclipse.*;
import com.choicemaker.cm.validation.eclipse.impl.*;
import java.util.*;
import com.choicemaker.cm.custom.mci.gend.MciRecords.*;
public class MothersImpl implements BaseRecord, Mothers {
private static Logger logger = Logger.getLogger(com.choicemaker.cm.custom.mci.gend.MciRecords.MothersImpl.class.getName());
public static MothersImpl[] __zeroArray = new MothersImpl[0];
public PatientImpl outer;
public PatientBase getOuter() {
return outer;
}
public void setOuter(PatientBase outer) {
this.outer = (PatientImpl)outer;
}
public boolean __v_mothers_maiden_name;
public boolean __v_mothers_dob;
public String mothers_maiden_name;
public boolean isMothers_maiden_nameValid() {
return __v_mothers_maiden_name;
}
public String getMothers_maiden_name() {
return mothers_maiden_name;
}
public Date mothers_dob;
public boolean isMothers_dobValid() {
return __v_mothers_dob;
}
public Date getMothers_dob() {
return mothers_dob;
}
public MothersImpl(MothersBase __o) {
mothers_maiden_name = __o.getMothers_maiden_name();
mothers_dob = __o.getMothers_dob();
}
public MothersImpl() {
}
public void computeValidityAndDerived(DerivedSource __src) {
java.lang.String __tmpStr;
try {
__v_mothers_maiden_name = Validators.isValid("mciRawLastNameValidator",mothers_maiden_name);
__v_mothers_dob = mothers_dob != null;
} catch(Exception __ex) {
logger.severe("Computing validity and derived of MothersImpl" + __ex);
}
}
public void resetValidityAndDerived(DerivedSource __src) {
}
public static MothersImpl instance() {
MothersImpl tmpInstance = new MothersImpl();
return tmpInstance;
}
}
