// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.custom.mci.gend.MciRecords;
import com.choicemaker.util.StringUtils;
import com.choicemaker.cm.custom.mci.encryption.*;
import com.choicemaker.cm.custom.mci.matching.*;
import com.choicemaker.cm.custom.mci.nameparser.*;
import com.choicemaker.cm.custom.mci.validation.*;
import com.choicemaker.cm.matching.en.*;
import com.choicemaker.cm.matching.en.us.*;
import com.choicemaker.cm.matching.gen.*;
import com.choicemaker.cm.validation.eclipse.*;
import com.choicemaker.cm.validation.eclipse.impl.*;
import java.util.*;
/**
 * Generated interface for the node type names. See package documentation for details.
 */
public interface Names extends NamesBase {
/**
 * Returns whether the value of the field sound_first_name is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field sound_first_name is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isSound_first_nameValid();
/**
 * Returns the value of sound_first_name.
 * @return  The value of sound_first_name.
*/
public String getSound_first_name();
/**
 * Returns whether the value of the field sound_last_name is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field sound_last_name is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isSound_last_nameValid();
/**
 * Returns the value of sound_last_name.
 * @return  The value of sound_last_name.
*/
public String getSound_last_name();
/**
 * Returns whether the value of the field parsedName is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field parsedName is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isParsedNameValid();
/**
 * Returns the value of parsedName.
 * @return  The value of parsedName.
*/
public NameParser getParsedName();
/**
 * Returns whether the value of the field nameF is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field nameF is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isNameFValid();
/**
 * Returns the value of nameF.
 * @return  The value of nameF.
*/
public String getNameF();
/**
 * Returns whether the value of the field nameM is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field nameM is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isNameMValid();
/**
 * Returns the value of nameM.
 * @return  The value of nameM.
*/
public String getNameM();
/**
 * Returns whether the value of the field nameL is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field nameL is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isNameLValid();
/**
 * Returns the value of nameL.
 * @return  The value of nameL.
*/
public String getNameL();
/**
 * Returns whether the value of the field nameMaidn is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field nameMaidn is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isNameMaidnValid();
/**
 * Returns the value of nameMaidn.
 * @return  The value of nameMaidn.
*/
public String getNameMaidn();
/**
 * Returns whether the value of the field nameT is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field nameT is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isNameTValid();
/**
 * Returns the value of nameT.
 * @return  The value of nameT.
*/
public String getNameT();
/**
 * Returns whether the value of the field mothersFirstName is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field mothersFirstName is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isMothersFirstNameValid();
/**
 * Returns the value of mothersFirstName.
 * @return  The value of mothersFirstName.
*/
public String getMothersFirstName();
/**
 * Returns whether the value of the field multiBirthOrder is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field multiBirthOrder is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isMultiBirthOrderValid();
/**
 * Returns the value of multiBirthOrder.
 * @return  The value of multiBirthOrder.
*/
public int getMultiBirthOrder();
/**
 * Returns whether the value of the field dob_y_m is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field dob_y_m is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isDob_y_mValid();
/**
 * Returns the value of dob_y_m.
 * @return  The value of dob_y_m.
*/
public String getDob_y_m();
/**
 * Returns whether the value of the field dobNumbers is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field dobNumbers is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isDobNumbersValid();
/**
 * Returns the value of dobNumbers.
 * @return  The value of dobNumbers.
*/
public int getDobNumbers();
/**
 * Returns whether the value of the field clean_sex is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field clean_sex is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isClean_sexValid();
/**
 * Returns the value of clean_sex.
 * @return  The value of clean_sex.
*/
public char getClean_sex();
}
