// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.custom.mci.gend.MciRecords;
import com.choicemaker.util.StringUtils;
import com.choicemaker.cm.custom.mci.encryption.*;
import com.choicemaker.cm.custom.mci.matching.*;
import com.choicemaker.cm.custom.mci.nameparser.*;
import com.choicemaker.cm.custom.mci.validation.*;
import com.choicemaker.cm.matching.en.*;
import com.choicemaker.cm.matching.en.us.*;
import com.choicemaker.cm.matching.gen.*;
import com.choicemaker.cm.validation.eclipse.*;
import com.choicemaker.cm.validation.eclipse.impl.*;
import java.util.*;
/**
 * Generated interface for the node type rel. See package documentation for details.
 */
public interface Rel extends RelBase {
/**
 * Returns whether the value of the field cleanAptNo is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field cleanAptNo is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isCleanAptNoValid();
/**
 * Returns the value of cleanAptNo.
 * @return  The value of cleanAptNo.
*/
public String getCleanAptNo();
/**
 * Returns whether the value of the field parsedStreet is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field parsedStreet is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isParsedStreetValid();
/**
 * Returns the value of parsedStreet.
 * @return  The value of parsedStreet.
*/
public ParsedAddress getParsedStreet();
/**
 * Returns whether the value of the field parsedHouseNumber is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field parsedHouseNumber is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isParsedHouseNumberValid();
/**
 * Returns the value of parsedHouseNumber.
 * @return  The value of parsedHouseNumber.
*/
public String getParsedHouseNumber();
/**
 * Returns whether the value of the field parsedStreetName is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field parsedStreetName is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isParsedStreetNameValid();
/**
 * Returns the value of parsedStreetName.
 * @return  The value of parsedStreetName.
*/
public String getParsedStreetName();
/**
 * Returns whether the value of the field parsedApartment is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field parsedApartment is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isParsedApartmentValid();
/**
 * Returns the value of parsedApartment.
 * @return  The value of parsedApartment.
*/
public String getParsedApartment();
/**
 * Returns whether the value of the field parsedPoBox is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field parsedPoBox is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isParsedPoBoxValid();
/**
 * Returns the value of parsedPoBox.
 * @return  The value of parsedPoBox.
*/
public String getParsedPoBox();
/**
 * Returns whether the value of the field phoneAsStreet is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field phoneAsStreet is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isPhoneAsStreetValid();
/**
 * Returns the value of phoneAsStreet.
 * @return  The value of phoneAsStreet.
*/
public String getPhoneAsStreet();
/**
 * Returns whether the value of the field clean_phone_no is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field clean_phone_no is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isClean_phone_noValid();
/**
 * Returns the value of clean_phone_no.
 * @return  The value of clean_phone_no.
*/
public String getClean_phone_no();
}
