// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated base interface for the node type contacts. See package documentation for details.
 */
public interface ContactsBase extends java.io.Serializable {
/**
 * Returns the outer node.
 * @return  The outer node.
*/
public PatientBase getOuter();
/**

 * @param  outer  The outer node.
*/
public void setOuter(PatientBase outer);
/**
 * Returns whether the value of the field relationship_cd is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field relationship_cd is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isRelationship_cdValid();
/**
 * Returns the value of relationship_cd.
 * @return  The value of relationship_cd.
*/
public String getRelationship_cd();
/**
 * Returns whether the value of the field last_name is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field last_name is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isLast_nameValid();
/**
 * Returns the value of last_name.
 * @return  The value of last_name.
*/
public String getLast_name();
/**
 * Returns whether the value of the field first_name is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field first_name is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isFirst_nameValid();
/**
 * Returns the value of first_name.
 * @return  The value of first_name.
*/
public String getFirst_name();
/**
 * Returns whether the value of the field sex_cd is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field sex_cd is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isSex_cdValid();
/**
 * Returns the value of sex_cd.
 * @return  The value of sex_cd.
*/
public char getSex_cd();
/**
 * Returns whether the value of the field phone_no_h is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field phone_no_h is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isPhone_no_hValid();
/**
 * Returns the value of phone_no_h.
 * @return  The value of phone_no_h.
*/
public String getPhone_no_h();
/**
 * Returns whether the value of the field phone_no_w is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field phone_no_w is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isPhone_no_wValid();
/**
 * Returns the value of phone_no_w.
 * @return  The value of phone_no_w.
*/
public String getPhone_no_w();
}
