// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;
import com.choicemaker.cm.custom.mci.encryption.*;
import com.choicemaker.cm.custom.mci.matching.*;
import com.choicemaker.cm.custom.mci.nameparser.*;
import com.choicemaker.cm.custom.mci.validation.*;
import com.choicemaker.cm.matching.en.*;
import com.choicemaker.cm.matching.en.us.*;
import com.choicemaker.cm.matching.gen.*;
import com.choicemaker.cm.validation.eclipse.*;
import com.choicemaker.cm.validation.eclipse.impl.*;
import java.util.*;
/**
 * Generated holder class for the node type ethnicity. See package documentation for details.
 */
public class EthnicityHolder implements com.choicemaker.cm.testobjects.mci.MciRecords.EthnicityBase, java.io.Serializable {
/** Default constructor. Initializes all all arrays for nested record to zero length arrays and all other values to their defaults (0/null). */public EthnicityHolder() {
}
/** Zero length array to be used by outer node class. */
public static final EthnicityHolder[] ZERO_ARRAY = new EthnicityHolder[0];
private PatientBase outer;
/**
 * Returns the outer node.
 * @return  The outer node.
*/
public PatientBase getOuter() {
return outer;
}
/**
 * Sets the outer node. This method should only be called by generated classes.
 * @param  outer  The outer node.
*/
public void setOuter(PatientBase outer) {
this.outer = outer;
}
private boolean ethnicity_cdValid;
protected String ethnicity_cd;
/**
 * Returns whether the value of the field ethnicity_cd is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field ethnicity_cd is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isEthnicity_cdValid() {
return ethnicity_cdValid;
}
/**
 * Returns the value of ethnicity_cd.
 * @return  The value of ethnicity_cd.
*/
public String getEthnicity_cd() {
return ethnicity_cd;
}
/**
 * Sets the value of ethnicity_cd.
 * @param  __v  The value of ethnicity_cd.
*/
public void setEthnicity_cd(String __v) {
this.ethnicity_cd = __v;
}
/** Copy constructor. Performs a deep copy of the nodes, but not the values.
 * @param  __o  The node to copy.
*/
public EthnicityHolder(EthnicityBase __o) {
ethnicity_cd = __o.getEthnicity_cd();
ethnicity_cdValid = __o.isEthnicity_cdValid();
}
}
