// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated base interface for the node type ethnicity. See package documentation for details.
 */
public interface EthnicityBase extends java.io.Serializable {
/**
 * Returns the outer node.
 * @return  The outer node.
*/
public PatientBase getOuter();
/**

 * @param  outer  The outer node.
*/
public void setOuter(PatientBase outer);
/**
 * Returns whether the value of the field ethnicity_cd is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field ethnicity_cd is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isEthnicity_cdValid();
/**
 * Returns the value of ethnicity_cd.
 * @return  The value of ethnicity_cd.
*/
public String getEthnicity_cd();
}
