// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated base interface for the node type events. See package documentation for details.
 */
public interface EventsBase extends java.io.Serializable {
/**
 * Returns the outer node.
 * @return  The outer node.
*/
public PatientBase getOuter();
/**

 * @param  outer  The outer node.
*/
public void setOuter(PatientBase outer);
/**
 * Returns whether the value of the field event_date is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field event_date is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isEvent_dateValid();
/**
 * Returns the value of event_date.
 * @return  The value of event_date.
*/
public Date getEvent_date();
/**
 * Returns whether the value of the field event_type_cd is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field event_type_cd is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isEvent_type_cdValid();
/**
 * Returns the value of event_type_cd.
 * @return  The value of event_type_cd.
*/
public String getEvent_type_cd();
/**
 * Returns whether the value of the field facility_id is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field facility_id is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isFacility_idValid();
/**
 * Returns the value of facility_id.
 * @return  The value of facility_id.
*/
public String getFacility_id();
/**
 * Returns whether the value of the field event_id is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field event_id is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isEvent_idValid();
/**
 * Returns the value of event_id.
 * @return  The value of event_id.
*/
public String getEvent_id();
/**
 * Returns whether the value of the field lab_date is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field lab_date is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isLab_dateValid();
/**
 * Returns the value of lab_date.
 * @return  The value of lab_date.
*/
public Date getLab_date();
}
