// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated interface for the node type events. See package documentation for details.
 */
public interface Events extends EventsBase {
/**
 * Returns whether the value of the field disease_cd is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field disease_cd is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isDisease_cdValid();
/**
 * Returns the value of disease_cd.
 * @return  The value of disease_cd.
*/
public String getDisease_cd();
}
