// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated interface for the node type frozen. See package documentation for details.
 */
public interface Frozen extends FrozenBase {
}
