// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated interface for the node type ids. See package documentation for details.
 */
public interface Ids extends IdsBase {
/**
 * Returns whether the value of the field patient_id_norm is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field patient_id_norm is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isPatient_id_normValid();
/**
 * Returns the value of patient_id_norm.
 * @return  The value of patient_id_norm.
*/
public String getPatient_id_norm();
}
