// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;
import com.choicemaker.cm.custom.mci.encryption.*;
import com.choicemaker.cm.custom.mci.matching.*;
import com.choicemaker.cm.custom.mci.nameparser.*;
import com.choicemaker.cm.custom.mci.validation.*;
import com.choicemaker.cm.matching.en.*;
import com.choicemaker.cm.matching.en.us.*;
import com.choicemaker.cm.matching.gen.*;
import com.choicemaker.cm.validation.eclipse.*;
import com.choicemaker.cm.validation.eclipse.impl.*;
import java.util.*;
/**
 * Generated interface for the node type ids. See package documentation for details.
 */
public interface Ids extends IdsBase {
/**
 * Returns whether the value of the field patient_id_norm is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field patient_id_norm is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isPatient_id_normValid();
/**
 * Returns the value of patient_id_norm.
 * @return  The value of patient_id_norm.
*/
public String getPatient_id_norm();
}
