// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated base interface for the node type ids. See package documentation for details.
 */
public interface IdsBase extends java.io.Serializable {
/**
 * Returns the outer node.
 * @return  The outer node.
*/
public PatientBase getOuter();
/**

 * @param  outer  The outer node.
*/
public void setOuter(PatientBase outer);
/**
 * Returns whether the value of the field patient_id is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field patient_id is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isPatient_idValid();
/**
 * Returns the value of patient_id.
 * @return  The value of patient_id.
*/
public String getPatient_id();
/**
 * Returns whether the value of the field identifier_type is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field identifier_type is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isIdentifier_typeValid();
/**
 * Returns the value of identifier_type.
 * @return  The value of identifier_type.
*/
public String getIdentifier_type();
/**
 * Returns whether the value of the field facility_id is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field facility_id is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isFacility_idValid();
/**
 * Returns the value of facility_id.
 * @return  The value of facility_id.
*/
public String getFacility_id();
}
