// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated interface for the node type indexAndOutstanding. See package documentation for details.
 */
public interface IndexAndOutstanding extends IndexAndOutstandingBase {
}
