// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated base interface for the node type patient. See package documentation for details.
 */
public interface IPatientRecordHolder extends com.choicemaker.cm.urm.base.IRecordHolder, PatientBase {}
