// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated holder class for the node type mothers. See package documentation for details.
 */
public class MothersHolder implements com.choicemaker.cm.testobjects.mci.MciRecords.MothersBase, java.io.Serializable {
/** Default constructor. Initializes all all arrays for nested record to zero length arrays and all other values to their defaults (0/null). */public MothersHolder() {
}
/** Zero length array to be used by outer node class. */
public static final MothersHolder[] ZERO_ARRAY = new MothersHolder[0];
private PatientBase outer;
/**
 * Returns the outer node.
 * @return  The outer node.
*/
public PatientBase getOuter() {
return outer;
}
/**

 * @param  outer  The outer node.
*/
public void setOuter(PatientBase outer) {
this.outer = outer;
}
private boolean mothers_maiden_nameValid;
protected String mothers_maiden_name;
/**
 * Returns whether the value of the field mothers_maiden_name is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field mothers_maiden_name is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isMothers_maiden_nameValid() {
return mothers_maiden_nameValid;
}
/**
 * Returns the value of mothers_maiden_name.
 * @return  The value of mothers_maiden_name.
*/
public String getMothers_maiden_name() {
return mothers_maiden_name;
}
/**

 * @param  __v  The value of mothers_maiden_name.
*/
public void setMothers_maiden_name(String __v) {
this.mothers_maiden_name = __v;
}
private boolean mothers_dobValid;
protected Date mothers_dob;
/**
 * Returns whether the value of the field mothers_dob is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field mothers_dob is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isMothers_dobValid() {
return mothers_dobValid;
}
/**
 * Returns the value of mothers_dob.
 * @return  The value of mothers_dob.
*/
public Date getMothers_dob() {
return mothers_dob;
}
/**

 * @param  __v  The value of mothers_dob.
*/
public void setMothers_dob(Date __v) {
this.mothers_dob = __v;
}
/** Copy constructor. Performs a deep copy of the nodes, but not the values.
 * @param  __o  The node to copy.
*/
public MothersHolder(MothersBase __o) {
mothers_maiden_name = __o.getMothers_maiden_name();
mothers_maiden_nameValid = __o.isMothers_maiden_nameValid();
mothers_dob = __o.getMothers_dob();
mothers_dobValid = __o.isMothers_dobValid();
}
}
