// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;
import com.choicemaker.cm.custom.mci.encryption.*;
import com.choicemaker.cm.custom.mci.matching.*;
import com.choicemaker.cm.custom.mci.nameparser.*;
import com.choicemaker.cm.custom.mci.validation.*;
import com.choicemaker.cm.matching.en.*;
import com.choicemaker.cm.matching.en.us.*;
import com.choicemaker.cm.matching.gen.*;
import com.choicemaker.cm.validation.eclipse.*;
import com.choicemaker.cm.validation.eclipse.impl.*;
import java.util.*;
/**
 * Generated base interface for the node type mothers. See package documentation for details.
 */
public interface MothersBase extends java.io.Serializable {
/**
 * Returns the outer node.
 * @return  The outer node.
*/
public PatientBase getOuter();
/**
 * Sets the outer node. This method should only be called by generated classes.
 * @param  outer  The outer node.
*/
public void setOuter(PatientBase outer);
/**
 * Returns whether the value of the field mothers_maiden_name is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field mothers_maiden_name is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isMothers_maiden_nameValid();
/**
 * Returns the value of mothers_maiden_name.
 * @return  The value of mothers_maiden_name.
*/
public String getMothers_maiden_name();
/**
 * Returns whether the value of the field mothers_dob is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field mothers_dob is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isMothers_dobValid();
/**
 * Returns the value of mothers_dob.
 * @return  The value of mothers_dob.
*/
public Date getMothers_dob();
}
