// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated base interface for the node type mothers. See package documentation for details.
 */
public interface MothersBase extends java.io.Serializable {
/**
 * Returns the outer node.
 * @return  The outer node.
*/
public PatientBase getOuter();
/**

 * @param  outer  The outer node.
*/
public void setOuter(PatientBase outer);
/**
 * Returns whether the value of the field mothers_maiden_name is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field mothers_maiden_name is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isMothers_maiden_nameValid();
/**
 * Returns the value of mothers_maiden_name.
 * @return  The value of mothers_maiden_name.
*/
public String getMothers_maiden_name();
/**
 * Returns whether the value of the field mothers_dob is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field mothers_dob is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isMothers_dobValid();
/**
 * Returns the value of mothers_dob.
 * @return  The value of mothers_dob.
*/
public Date getMothers_dob();
}
