// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;
import com.choicemaker.cm.custom.mci.encryption.*;
import com.choicemaker.cm.custom.mci.matching.*;
import com.choicemaker.cm.custom.mci.nameparser.*;
import com.choicemaker.cm.custom.mci.validation.*;
import com.choicemaker.cm.matching.en.*;
import com.choicemaker.cm.matching.en.us.*;
import com.choicemaker.cm.matching.gen.*;
import com.choicemaker.cm.validation.eclipse.*;
import com.choicemaker.cm.validation.eclipse.impl.*;
import java.util.*;
/**
 * Generated base interface for the node type names. See package documentation for details.
 */
public interface NamesBase extends java.io.Serializable {
/**
 * Returns the outer node.
 * @return  The outer node.
*/
public PatientBase getOuter();
/**
 * Sets the outer node. This method should only be called by generated classes.
 * @param  outer  The outer node.
*/
public void setOuter(PatientBase outer);
/**
 * Returns whether the value of the field first_name is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field first_name is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isFirst_nameValid();
/**
 * Returns the value of first_name.
 * @return  The value of first_name.
*/
public String getFirst_name();
/**
 * Returns whether the value of the field middle_name is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field middle_name is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isMiddle_nameValid();
/**
 * Returns the value of middle_name.
 * @return  The value of middle_name.
*/
public String getMiddle_name();
/**
 * Returns whether the value of the field last_name is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field last_name is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isLast_nameValid();
/**
 * Returns the value of last_name.
 * @return  The value of last_name.
*/
public String getLast_name();
/**
 * Returns whether the value of the field dob is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field dob is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isDobValid();
/**
 * Returns the value of dob.
 * @return  The value of dob.
*/
public Date getDob();
/**
 * Returns whether the value of the field sex_cd is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field sex_cd is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isSex_cdValid();
/**
 * Returns the value of sex_cd.
 * @return  The value of sex_cd.
*/
public char getSex_cd();
/**
 * Returns whether the value of the field facility_id is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field facility_id is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isFacility_idValid();
/**
 * Returns the value of facility_id.
 * @return  The value of facility_id.
*/
public String getFacility_id();
}
