// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated base interface for the node type providers. See package documentation for details.
 */
public interface ProvidersBase extends java.io.Serializable {
/**
 * Returns the outer node.
 * @return  The outer node.
*/
public PatientBase getOuter();
/**

 * @param  outer  The outer node.
*/
public void setOuter(PatientBase outer);
/**
 * Returns whether the value of the field provider_id is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field provider_id is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isProvider_idValid();
/**
 * Returns the value of provider_id.
 * @return  The value of provider_id.
*/
public String getProvider_id();
/**
 * Returns whether the value of the field facility_id is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field facility_id is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isFacility_idValid();
/**
 * Returns the value of facility_id.
 * @return  The value of facility_id.
*/
public String getFacility_id();
}
