// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;
import com.choicemaker.cm.custom.mci.encryption.*;
import com.choicemaker.cm.custom.mci.matching.*;
import com.choicemaker.cm.custom.mci.nameparser.*;
import com.choicemaker.cm.custom.mci.validation.*;
import com.choicemaker.cm.matching.en.*;
import com.choicemaker.cm.matching.en.us.*;
import com.choicemaker.cm.matching.gen.*;
import com.choicemaker.cm.validation.eclipse.*;
import com.choicemaker.cm.validation.eclipse.impl.*;
import java.util.*;
/**
 * Generated holder class for the node type providers. See package documentation for details.
 */
public class ProvidersHolder implements com.choicemaker.cm.testobjects.mci.MciRecords.ProvidersBase, java.io.Serializable {
/** Default constructor. Initializes all all arrays for nested record to zero length arrays and all other values to their defaults (0/null). */public ProvidersHolder() {
}
/** Zero length array to be used by outer node class. */
public static final ProvidersHolder[] ZERO_ARRAY = new ProvidersHolder[0];
private PatientBase outer;
/**
 * Returns the outer node.
 * @return  The outer node.
*/
public PatientBase getOuter() {
return outer;
}
/**
 * Sets the outer node. This method should only be called by generated classes.
 * @param  outer  The outer node.
*/
public void setOuter(PatientBase outer) {
this.outer = outer;
}
private boolean provider_idValid;
protected String provider_id;
/**
 * Returns whether the value of the field provider_id is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field provider_id is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isProvider_idValid() {
return provider_idValid;
}
/**
 * Returns the value of provider_id.
 * @return  The value of provider_id.
*/
public String getProvider_id() {
return provider_id;
}
/**
 * Sets the value of provider_id.
 * @param  __v  The value of provider_id.
*/
public void setProvider_id(String __v) {
this.provider_id = __v;
}
private boolean facility_idValid;
protected String facility_id;
/**
 * Returns whether the value of the field facility_id is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field facility_id is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isFacility_idValid() {
return facility_idValid;
}
/**
 * Returns the value of facility_id.
 * @return  The value of facility_id.
*/
public String getFacility_id() {
return facility_id;
}
/**
 * Sets the value of facility_id.
 * @param  __v  The value of facility_id.
*/
public void setFacility_id(String __v) {
this.facility_id = __v;
}
/** Copy constructor. Performs a deep copy of the nodes, but not the values.
 * @param  __o  The node to copy.
*/
public ProvidersHolder(ProvidersBase __o) {
provider_id = __o.getProvider_id();
provider_idValid = __o.isProvider_idValid();
facility_id = __o.getFacility_id();
facility_idValid = __o.isFacility_idValid();
}
}
