// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated base interface for the node type race. See package documentation for details.
 */
public interface RaceBase extends java.io.Serializable {
/**
 * Returns the outer node.
 * @return  The outer node.
*/
public PatientBase getOuter();
/**

 * @param  outer  The outer node.
*/
public void setOuter(PatientBase outer);
/**
 * Returns whether the value of the field race_cd is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field race_cd is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isRace_cdValid();
/**
 * Returns the value of race_cd.
 * @return  The value of race_cd.
*/
public String getRace_cd();
}
