// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.cm.testobjects.mci.MciRecords;
import com.choicemaker.util.StringUtils;









import java.util.*;
/**
 * Generated interface for the node type race. See package documentation for details.
 */
public interface Race extends RaceBase {
}
