USE [EPI_MPIMODELING]
GO

/****** Object:  Table [dbo].[CMT_NAMED_CONFIG2]    Script Date: 1/15/2019 7:29:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CMT_NAMED_CONFIG2](
	[NC_ID] [numeric](19, 0) NOT NULL,
	[ABA_BLOCKSET] [int] NULL,
	[ABA_SINGLESET] [int] NULL,
	[ABA_MATCHES] [int] NULL,
	[ABA_SINGLETABLE] [int] NULL,
	[BLOCKING_CONF] [varchar](255) NULL,
	[NC_DESC] [varchar](255) NULL,
	[NC_NAME] [varchar](255) NOT NULL,
	[DATA_SOURCE] [varchar](255) NULL,
	[HIGH_THRESHOLD] [real] NULL,
	[CLASS] [varchar](255) NULL,
	[LOW_THRESHOLD] [real] NULL,
	[MODEL] [varchar](255) NULL,
	[OABA_INTERVAL] [int] NULL,
	[OABA_BLOCKSIZE] [int] NULL,
	[OABA_CHUNKSIZE] [int] NULL,
	[OABA_MATCHES] [int] NULL,
	[OABA_OVERSIZE] [int] NULL,
	[OABA_SINGLE] [int] NULL,
	[OABA_OSFIELDS] [int] NULL,
	[OPTLOCK] [int] NULL,
	[QUERY_DBCONF] [varchar](255) NULL,
	[QUERY_RS_DEDUPED] [bit] NULL,
	[QUERY_SQL] [varchar](255) NULL,
	[RS_TYPE] [varchar](255) NULL,
	[REF_DBACC] [varchar](255) NULL,
	[REF_DBCONF] [varchar](255) NULL,
	[REF_DBREAD] [varchar](255) NULL,
	[REF_SQL] [varchar](255) NULL,
	[RIGOR] [varchar](255) NULL,
	[FILE_URI] [varchar](255) NULL,
	[SVR_FILES_COUNT] [int] NULL,
	[SVR_FILE_ENTRIES] [int] NULL,
	[SVR_THREADS] [int] NULL,
	[TASK] [varchar](255) NULL,
	[FORMAT] [varchar](255) NULL,
	[GRAPH] [varchar](255) NULL,
	[UUID] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[NC_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CMT_NAMED_CONFIG2] ADD  DEFAULT ((0)) FOR [OPTLOCK]
GO

ALTER TABLE [dbo].[CMT_NAMED_CONFIG2] ADD  DEFAULT ((0)) FOR [QUERY_RS_DEDUPED]
GO


